settings:
    vat_tag: 1105 # Код типа НДС по 54-ФЗ   (see Helper\FZ54)
    tax_system: 0 # Система налогообложения (see Helper\FZ54)

order:
    link_lifetime: '20 minutes' # Время действия ссылки на оплату заказа по умолчанию

    # Если true, срок действия ссылки на оплату на шлюзе будет браться из valid_through заказа, если это значение задано
    # Если false или valid_through у заказа не задан, срок действия заказа на шлюзе будет передаваться из link_lifetime
    use_valid_through: true

# Платежные шлюзы
gateway:

    sberbank:
        userName: 'merchant-api'
        password: 'xxx'
        test_mode: 1
        success_url: 'https://example.org/payment/success.html'
        fail_url: 'https://example.org/payment/fail.html'

        send_items: 1         # Нужно ли отправлять содержимое корзины на шлюз вместе с остальными параметрами заказа
        auto_fiscalization: 1 # На шлюзе настроена автоматическая фискализация чеков (например, Сбербанк + Атол.Онлайн)

        # Параметр, который будет передаваться на шлюз вместо номера заказа.
        # Сбербанк запрещает обновление уже зарегистрированного заказа, поэтому если может понадобиться
        # обновление заказа уже после регистрации на шлюзе, лучше использовать параметр, отличный от order_number
#        orderNumber: 'transaction_id'

#        callback_use_checksum: 1 # Настроено получение уведомлений обратного вызова с контрольной суммой
#        secret_key: 'top_secret' # Секретный ключ для проверки корректности контрольной суммы в callback-запросах

    SberbankSBP:
        memberID:
        clientID: # https://api.developer.sber.ru/how-to-use/create_app
        idQR:
        tid:
        clientSecret: # https://api.developer.sber.ru/how-to-use/create_app
        certPath: # https://api.developer.sber.ru/how-to-use/create_certificate
        certPassword:

    monetaru:
        MNT_ID: 12345678
        DATA_INTEGRITY_CODE: 'secret_code'
        currency: 'RUB' # Код валюты по ISO 4217 (see Helper\ISO4217)
        method: 'POST'
        test_mode: 1
        fail_url: 'https://example.org/payment_fail.html'
        success_url: 'https://example.org/payment_success.html'

# Онлайн-кассы
till:
    modulkassa:
        test_mode: 1
        login: '12345678-1234-1234-1234-123456789012'
        password: 'xxx'

        # Маска URL для уведомлений от сервера фискализации
        responseURL: 'https://example.org/payment/callback.php?transaction_id={{transaction_id}}'
#        responseURL: '/payment/callback.php?{{hash}}'
#        responseURL: '/payment/callbackURL/{{hash}}'

# Параметры БД
database:
      driver: 'mysql'
      host: 'localhost'
      database: 'db_name'
      username: 'db_user'
      password: 'db_password'
      charset: 'utf8'
      collation: 'utf8_general_ci'
      prefix: 'rupay_'

# Классы шлюза и кассы по умолчанию
# Если заданы, объекты можно будет создавать без аргументов: Gateway::create() и Till::create() соответственно
default:
    gateway: 'sberbank'
    till: 'modulkassa'
